server:
  port: 4549
  tomcat:
    max-threads: 800
    accept-count: 30000
    min-spare-threads: 20
    max-connections: 30000
#  ssl:
#    key-store: admin.btcjag.pfx
#    key-store-password: XU2pc15n
#    keyStoreType: PKCS12
spring:
  messages:
    basename: static/i18n/messages
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: bitcentre@btcjag.com
    password: BGzYP99hmHqBMFd
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  redis:
    host: 127.0.0.1
    port: 6379
    password: linglouyi
    database: 0
    timeout: 200000ms
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
        max-active: 8
        min-idle: 0

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_hoe?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: ewrqersdfsdxcvfafdafsdafgw
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 12
      connection-timeout: 200000
      idle-timeout: 3000000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: HoeHikariCP

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
